---
- name: Set Vivaldi default application
  community.general.gio_mime:
    mime_type: "{{ mimetype }}"
    handler: vivaldi-stable.desktop
  loop: "{{ vivaldi_mimetypes }}"
  loop_control:
    loop_var: mimetype
  become: true
  become_user: "{{ item }}"
